# Generated by Django 3.2.11 on 2022-02-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('run', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Running', 'running'), ('Success', 'success'), ('Failed', 'failed')], default='Pending', max_length=50)),
                ('started_at', models.DateTimeField(null=True)),
                ('done_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
