# Generated by Django 3.2.11 on 2022-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='upload_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Downloading', 'downloading'), ('Uploading', 'running'), ('Success', 'success'), ('Failed', 'failed')], default='Pending', max_length=50),
        ),
    ]
