# Generated by Django 3.2.11 on 2022-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220210_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Downloading', 'downloading'), ('Uploading', 'uploading'), ('Success', 'success'), ('Failed', 'failed')], default='Pending', max_length=50),
        ),
    ]
